export const getAllUsers_Url = "http://localhost:8080/user/getAllUsers"
export const getUser_Url = "http://localhost:8080/user/getUser"
export const deleteUser_Url = "http://localhost:8080/user/deleteUser/"
export const addUser_Url = "http://localhost:8080/user/newUser"
export const editUser_Url = "http://localhost:8080/user/updateUser"